### ISSUE TITLE
MCR and IP assignment to data centre

### ISSUE THREAD

**Issue by fjstroud** [megaport/terraform-provider-megaport#13]
Is there an approach to specifiy the /30 addresses for the bgp peer connections linking MCR to a port?

**Comment by venotar** [comment]
Would love to see this capability

**Comment by pushee** [comment]
Hi @venotar this feature is included in an upcoming release which is currently under review, hopefully out within the next couple of weeks.

**Comment by pushee** [comment]
Hi @fjstroud @venotar,

Following our 0.2.0 beta release, you should now be able to achieve this by setting the `megaport_vxc.a_end_mcr_configuration.ip_addresses` parameter.

See [here](https://github.com/megaport/terraform-provider-megaport/blob/main/docs/resources/megaport_vxc.md) .
