### ISSUE TITLE
[BUG] Issues with documentation

### ISSUE THREAD

**Issue by gfysaris** [megaport/terraform-provider-megaport#140]
**Describe the bug**
Errors in Documentation

**Terraform and Provider Version**
Megaport Provider version: 1.1.1

**Additional context**
Nested schema names are wrong.

- Nested Schema for a_end_partner_config.vrouter_config.interfaces.vlan ==> Nested Schema for a_end_partner_config.vrouter_config.interfaces.bfd
- Nested Schema for a_end_partner_config.vrouter_config.interfaces.vlan ==> Nested Schema for a_end_partner_config.vrouter_config.interfaces.bgp_connections
- Nested Schema for a_end_partner_config.vrouter_config.interfaces.vlan ==> Nested Schema for a_end_partner_config.vrouter_config.interfaces.ip_routes

![image](https://github.com/user-attachments/assets/bb9a6031-e123-4d3f-bd99-37deff7e69b5)

**Comment by gfysaris** [comment]
Same issue on b_end_partner_config documentation

**Comment by mega-alex** [comment]
I believe this is an issue with the docs generator, but looking into it further. Weirdly enough if you look at the markdown you can see that the anchor tag is correct, but the text is not.

```
<a id="nestedatt--a_end_partner_config--vrouter_config--interfaces--bgp_connections"></a>
### Nested Schema for `a_end_partner_config.vrouter_config.interfaces.vlan`
```

**Comment by mega-alex** [comment]
It appears to have been [this issue](https://github.com/hashicorp/terraform-plugin-docs/issues/380), I've bumped the version and regenerated the docs which seems to have fixed the incorrect field.
