### ISSUE TITLE
[FEATURE REQUEST] Azure Cloud VXC - Support "Azure Single VLAN" in Terraform Configuration

### ISSUE THREAD

**Issue by efettero** [megaport/terraform-provider-megaport#159]
**Is your feature request related to a problem? Please describe.**
There does not seem to be a way currently with the Megaport Terraform provider to configure the "Azure Single VLAN" setting as you can from the portal. I see `b_end_partner_config.azure_config.peers.vlan` but I do not believe this is the parameter that configures this. `b_end_partner_config.azure_config.peers` contains other required parameters, not just the VLAN.

To test this out I deployed an Azure VXC from the portal with "Azure Single VLAN" set to `210`. I then used the API to list the products on the account so I could see what attributes have `210`. The screenshot under "Additional context" below showcases where this is being set.

**Describe the solution you'd like**
If this is not already configurable via Terraform we would like it to be.

**Is this feature available in the Megaport Portal?**
Yes

**Additional context**

![image](https://github.com/user-attachments/assets/3c11f3b0-4c76-4075-9d13-51acf05a165c)

**Comment by mega-alex** [comment]
You can set the `b_end` attribute `inner_vlan` to accomplish what the portal is doing. Let me know if that resolves this issue for you.

**Comment by efettero** [comment]
Hey @mega-alex, thank you for the response here. Unfortunately I cannot test this at the moment as I heard from support earlier in the week that deploying Azure VXCs into staging currently is not working, and I can confirm.

I will test this out within the next few weeks when we have an Azure VXC to provision in production, thank you!

**Comment by mega-alex** [comment]
Hey did you get a chance to test this?

**Comment by efettero** [comment]
Hey @mega-alex, sorry for the delayed response here. Yes, we were just able to confirm that this did the trick for us. Much appreciated!
