### ISSUE TITLE
[BUG] Cannot set Contract Terms to "No Minimum Term

### ISSUE THREAD

**Issue by vcorte02** [megaport/terraform-provider-megaport#169]
**Describe the bug**
Our current contract terms are No Minimum Term but there is no option for it. The only option are 1, 12, 24, and 36. 

**Terraform and Provider Version**
1.2.0

**Terraform File and Steps to Reproduce**
If possible please provide a `.tf` file that can reproduce the issue, along with any changes you made to trigger the issue. If there is an API error that is returned, please provide the `trace_id` so that we can look up the request.
data "megaport_location" "kb_akl" {
  name    = "Datacom 6 Orbit"
}

resource "megaport_mcr" "kb_akl_mcr" {
  product_name         = "KB_AKL_MCR01"
  port_speed           = 10000
  location_id          = data.megaport_location.kb_akl.id
  contract_term_months = 1
  asn = 133937
}

**Additional context**

**Comment by mega-alex** [comment]
Hi there, the `1` month term is month to month / no minimum term.
