### ISSUE TITLE
Specify (or pass through) AWS DX Connection Name

### ISSUE THREAD

**Issue by kevinmartin** [megaport/terraform-provider-megaport#17]
When creating a `megaport_aws_connection`, the AWS DX Connection name defaults to "MEGAPORT".

In the Megaport console, the VXC name is passed through to the AWS DX Connection name. It would be nice to either pass through the VXC name to the AWS DX Connection, or to be able to specify it in the Terraform.

![image](https://user-images.githubusercontent.com/510957/150046113-b53c981c-2417-4c49-85ac-0a1dbb66bca1.png)

Example code:
```hcl
resource "megaport_aws_connection" "example" {
  vxc_name   = "example"
  rate_limit = 100

  a_end {
    requested_vlan = 1234
  }

  csp_settings {
    attached_to          = data.megaport_port.example.id
    requested_product_id = data.megaport_partner_port.example.id
    requested_asn        = 65002
    amazon_asn           = 65001
    amazon_account       = 123456789123
    hosted_connection    = true
  }
}

```

**Comment by flackon** [comment]
connection_name added in v0.2.4
