### ISSUE TITLE
[FEATURE REQUEST] Option to select No Minimum Term for VXC

### ISSUE THREAD

**Issue by gopurx** [megaport/terraform-provider-megaport#184]
**Is your feature request related to a problem? Please describe.**
As per terraform docs, there is no option available to choose "No Minimum Term" option while configuring VXC.

**Describe the solution you'd like**
Making `contract_term_months` attribute an optional parameter and default the config to make connection as no minimum term for contract

**Is this feature available in the Megaport Portal?**
Yes, this option is available today to select while configuring VXC

**Additional context**

**Comment by gopurx** [comment]
Ahh, realized from API docs that passing this attribute as 1 will put the connection to "No Minimum Term". It will be helpful to put a liner in terraform docs to reflect the same.

**Comment by mega-alex** [comment]
Thanks for the suggestion, I agree we could put that into the docs!
