### ISSUE TITLE
Upgrade guide from 0.1.10 to 0.2.1

### ISSUE THREAD

**Issue by r0b6** [megaport/terraform-provider-megaport#22]
Is there a upgrade guide for megaport provider version 0.1.10 to 0.2.1?

**Comment by steve-exley** [comment]
Not specifically, it is the same as upgrading any other provider.

The release notes for [0.2.0 ](https://github.com/megaport/terraform-provider-megaport/releases/tag/v0.2.0) detail the breaking changes which only affect a few fields. The same information is in the [CHANGELOG.md](https://github.com/megaport/terraform-provider-megaport/blob/main/CHANGELOG.md). 

We would recommend using the [CHANGELOG.md](https://github.com/megaport/terraform-provider-megaport/blob/main/CHANGELOG.md) to compare changes between current and intended versions when making a decision whether to upgrade.
