### ISSUE TITLE
[Error] Unsupported Block Type

### ISSUE THREAD

**Issue by victor-cortez0315** [megaport/terraform-provider-megaport#23]
Trying to configure MCR with BGP VXCs and the a_end_mcr_configuration block is not supported.

**Comment by steve-exley** [comment]
@victor-cortez0315 , Please could you post an example Terraform block of what you are trying to do.

**Comment by victor-cortez0315** [comment]
resource "megaport_aws_connection" "kb_aws_vxc" {
  vxc_name   = var.aws_vxc_name
  rate_limit = var.aws_rate_limit

  a_end {
    requested_vlan = var.aws_requested_vlan
  }

  a_end_mcr_configuration {
    ip_addresses = var.a_end_ip

    bgp_connection {
      peer_asn         = var.peer_asn
      local_ip_address = var.bgp_local_ip
      peer_ip_address  = var.bgp_peer_ip
    }
  }

  csp_settings {
    attached_to          = var.aws_attached_to
    requested_product_id = data.megaport_partner_port.kb_aws_megaport.id
    requested_asn        = var.aws_requested_asn
    amazon_asn           = var.amazon_asn
    amazon_account       = var.amazon_account
    hosted_connection    = var.hosted_connection
  }
}

**Comment by vcorte02** [comment]
var.a_end_ip is a single string. Should it be a slice?

**Comment by victor-cortez0315** [comment]
It is a single string. Should it be a slice?
