### ISSUE TITLE
ability to set admin lock on resources created by terraform

### ISSUE THREAD

**Issue by mi1os** [megaport/terraform-provider-megaport#3]
This is something I am missing in the provider. 

Our use case is - all our production MCRs+VXCs are admin locked to limit number of people who have ability to change them manually. With the terraform provider I would also lock all other resources to prevent manual changes and force people to use terraform instead.

**Comment by HammoTime** [comment]
This should be a relatively straight forward change but will require a bit of effort to get all the code written.

We will hopefully get this included in our next sprint. I'll provide an update when it gets included during planning.

**Comment by arctiqhart** [comment]
+1

**Comment by mega-alex** [comment]
This is now be available in the `v1.0.0` release
