### ISSUE TITLE
Importing VxC resource not implemented

### ISSUE THREAD

**Issue by SuperPopT** [megaport/terraform-provider-megaport#35]
Hi Team,
We have tried to import VxC resource using the latest version of your terraform provider 0.2.9 and we get the following error:
`"Error: resource megaport_vxc doesn't support import"`
We can import Ports and MCRs resources with no issues. We confirmed with Megaport support that this feature is not implemented yet and we would like to know if there is any plan to develop it and any estimation, if it is possible.

Thanks.
Regards.

**Comment by kaon1** [comment]
I would also like to +1 this feature request. I currently have an MCR with some hosted connections/vxcs which I would like to manage via terraform moving forward. 

Is the current recommendation to manually delete the resources and re-build them with terraform?

**Comment by mega-alex** [comment]
You can now import VXCs and other resources with the `v1.0.0` provider
