### ISSUE TITLE
Understanding Terraform Destroy - Could not find Connection with ID

### ISSUE THREAD

**Issue by CarmineDeloitte** [megaport/terraform-provider-megaport#39]
Hello, 

I'm creating a megaport_aws_connection using the megaport terraform provider, and I'm successfully creating the connection.
Here is my main.tf

```terraform
data "megaport_location" "eu-west-3" {
  name = "Telehouse Paris Voltaire TH2"

}


data "megaport_partner_port" "aws_port" {
  company_name   = "AWS"
  connect_type   = "AWSHC"
  product_name   = "EU (Frankfurt) (eu-central-1)"
  diversity_zone = "blue"
  location_id    = data.megaport_location.eu-west-3.id
}



resource "megaport_aws_connection" "aws_vxc" {
  vxc_name   = "Terraform Example - AWS VXC"
  rate_limit = 200
  destroy_connection = true

  a_end {
    port_id        = "<my_port_id>"
    requested_vlan = 316

  }

  csp_settings {
    connection_name = "Terraform Example - AWS VXC"
    requested_product_id = data.megaport_partner_port.aws_port.id
    requested_asn        = 65001
    amazon_asn           = 64512
    amazon_account       = "88888888"
    hosted_connection = true
  }
}

resource "aws_dx_connection_confirmation" "confirmation" {
  connection_id = megaport_aws_connection.aws_vxc.connection_id

}

```

In my TF, I also use the aws_dx_connection_confirmation to confirm the direct connection creation. 
On this side, everything is working correctly, until I want to destroy everything to clean resources using terraform destroy.

Here is the error:

```
aws_dx_private_virtual_interface.VIF-TURIN-OPC-TEST: Still destroying... [id=dxvif-fgyx1fwu, 2m30s elapsed]
aws_dx_private_virtual_interface.VIF-TURIN-OPC-TEST: Destruction complete after 2m37s
aws_dx_connection_confirmation.confirmation: Destroying... [id=dxcon-fg3xnnuf]
aws_dx_connection_confirmation.confirmation: Destruction complete after 0s
megaport_aws_connection.aws_vxc: Destroying... [id=200bcccf-xxx-xxx-xxxxxxxxxx]
╷
│ Error: DirectConnectClientException: Could not find Connection with ID dxvif-fgyx1fwu
│       status code: 400, request id: b3ccf2c5-xxxx-xxx-xxx-xxxx│ 
│ 
╵
```

I'm using the flag destroy_connection = true that should destroy the AWS direct connect, but I'm not understanding why is saying that there isn't any Connection with ID dxcon-xxxxxx while on my AWS account the DX is there. 
Look also at the status code, is giving a 400 on a different id.
Here:
```
megaport_aws_connection.aws_vxc: Destroying... [id=200bcccf-xxx-xxx-xxxxxxxxxx]
```
Is trying to destroy the id=200bccc but right after is looking for a request id b3ccf2c5.

Can someone help me to understand how to properly destroy the megaport resources?

Thanks!

**Comment by CarmineDeloitte** [comment]
Any news on this topic?

**Comment by mega-alex** [comment]
Would you mind giving this a try with the new `v1.0.0` provider. It should handle resource destruction better, and if you run into any issues it has more verbose logging you can enable with `TF_LOG=debug`.

**Comment by mega-alex** [comment]
Going to close this issue as it should be solved in the newest versions of the provider
