### ISSUE TITLE
megaport_aws_connection b_end vlan changed

### ISSUE THREAD

**Issue by per-lind** [megaport/terraform-provider-megaport#44]
Today when running terraform the b_end on my megaport_aws_connection aws connecten have changed. Possible after maintenance?

# megaport_aws_connection.aws_vxc has changed
~ resource "megaport_aws_connection" "aws_vxc" {
      ~ b_end               = [
          - {
              - assigned_asn   = 0
              - assigned_vlan  = **3861**
              - location       = "Interxion FRA6"
              - name           = "EU (Frankfurt) (eu-central-1)"
              - owner_uid      = "xxx"
              - port_id        = "xxx"
              - requested_vlan = 3861
            },
          + {
              + assigned_asn   = 0
              + assigned_vlan  = 3034
              + location       = "Interxion FRA6"
              + name           = "EU (Frankfurt) (eu-central-1)"
              + owner_uid      = "xxx"
              + port_id        = "xxx"
              + requested_vlan = 3861
            },
        ]
        id                  = "xxx"
        # (13 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

This caused terraform to force recreation of
  # aws_dx_transit_virtual_interface.vif_megafra6 must be replaced
-/+ resource "aws_dx_transit_virtual_interface" "vif_megafra6" {
      ~ amazon_address      = "169.254.96.1/29" -> (known after apply)
      ~ amazon_side_asn     = "64515" -> (known after apply)
      ~ arn                 = "xxx" -> (known after apply)
      ~ aws_device          = "INX6-3q2cwdzlvn3qr" -> (known after apply)
      ~ bgp_auth_key        = "xxx" -> (known after apply)
      ~ customer_address    = "169.254.96.6/29" -> (known after apply)
      ~ id                  = "dxvif-ffxguvj0" -> (known after apply)
      ~ jumbo_frame_capable = true -> (known after apply)
        name                = "megaport_fra6_tgw_fra"
      - sitelink_enabled    = false -> null
      - tags                = {} -> null
      ~ tags_all            = {} -> (known after apply)
      ~ vlan                = 3861 -> 3034 # forces replacement
        # (5 unchanged attributes hidden)
    }

However when I check in AWS the interface is running on VLAN 3861. What is going on here?

**Comment by mega-alex** [comment]
We've reworked a lot of the code around VXC creation and updates. I'm going to close this issue as it likely is fixed, but feel free to reopen it if the problem persists.
