### ISSUE TITLE
Required Roles and Access for Cloud

### ISSUE THREAD

**Issue by arctiqhart** [megaport/terraform-provider-megaport#5]
Hi there,

Would be great to have Principle of Least Privilege for the specific cloud environments service accounts. For example, when creating a GCP SA, which IAM roles are required to standup all requirements (VPC, subnet, etc.)

**Comment by steve-exley** [comment]
We hear you. 

Since we do not advocate for, create or change any roles, this is not something we can control. 

Specifically what are you proposing here?

**Comment by steve-exley** [comment]
Closing stale issue
