### ISSUE TITLE
Bug:  auto_create_private_peering does not work from Azure to Megaport via VXC

### ISSUE THREAD

**Issue by haowei99** [megaport/terraform-provider-megaport#52]
```
resource "megaport_azure_connection" "azure_vxc" {
    vxc_name   = "${var.prefix} Terraform Example - Azure VXC"
    rate_limit = var.azure_expressroute_bandwidth

    a_end {
        port_id        = data.megaport_mcr.mcr.id
        requested_vlan = 0
    }

    csp_settings {
        service_key                   = "<REDACTED>"
        auto_create_private_peering   = true
        
#         private_peering {
#             peer_asn         = "12076"
#             primary_subnet   = "10.0.2.0/30"
#             secondary_subnet = "10.0.3.0/30"
#             requested_vlan   = 100
#         }
    }
    
}
```

When creating the VXC connection to MCR, auto_create_private_peering does not work. I was following the example guide here: https://github.com/megaport/terraform-provider-megaport/blob/main/examples/cloud_to_cloud_aws_azure/megaport.tf#L46

The error I get:
```
╷
│ Error: Validation failed: Azure: invalid vlan, Validation of b_csp_request failed
│ 
│   with megaport_azure_connection.azure_vxc,
│   on megaport.tf line 6, in resource "megaport_azure_connection" "azure_vxc":
│    6: resource "megaport_azure_connection" "azure_vxc" {
│ 
╵
```

It looks like no one has gotten that yet when searched on Google. 

After a whole day of debugging the workaround is to simply define your own private peering:

private_peering {
             peer_asn         = "12076"
             primary_subnet   = "10.0.2.0/30"
             secondary_subnet = "10.0.3.0/30"
             requested_vlan   = 100
}

**Comment by mega-alex** [comment]
This should be fixed in the latest versions of the provider. If there are still issues, feel free to reopen this ticket.
