### ISSUE TITLE
Error with Data sources

### ISSUE THREAD

**Issue by luduga** [megaport/terraform-provider-megaport#54]
Trying to get data from current Megaport infra deployed out of terraform, I always get the same error during planning phase. I've even tried with the same example from the documentation.  Issue is always the same, no matter if I try with a MCR, VXC or MEgaport. 
However, If I create a resource and try to deploy it, I don't get any issue:

Example of the issue:

`Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: : 
│ 
│   with data.megaport_location.my_loc,
│   on import.tf line 1, in data "megaport_location" "my_loc":
│    1: data "megaport_location" "my_loc" {
│ `

Code in terraform file:

`data "megaport_location" "my_loc" {
  name = "NextDC B1"
}

output "id" {
  value = data.megaport_location.my_loc.id
}`

**Comment by luduga** [comment]
Correction. The code I originally posted wasn't correct. I've fixed the typo but error is still the same:

New code:

`terraform {
  required_providers {
    megaport = {
      source  = "megaport/megaport"
      version = "0.4.1"
    }
  }
}

provider "megaport" {
  access_key            = "---"
  secret_key            = "---"
  accept_purchase_terms = true
  delete_ports          = true
  environment           = "staging"
}

data "megaport_location" "my_loc" {
  name        = "NextDC B1"
  market_code = "AU"
  has_mcr     = true
}
`

And same error:

`data.megaport_location.my_loc: Reading...

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: : 
│ 
│   with data.megaport_location.my_loc,
│   on import.tf line 18, in data "megaport_location" "my_loc":
│   18: data "megaport_location" "my_loc" {
│ 
╵`

**Comment by mega-alex** [comment]
Hi there, the issue should now be fixed on the `main` branch. We will release a new version of the provider soon that contains the fix.
