### ISSUE TITLE
MCR import does not include prefix list

### ISSUE THREAD

**Issue by zjaniga** [megaport/terraform-provider-megaport#62]
After importing an MCR the prefix list is not included.

**Comment by mega-alex** [comment]
Hi there, could you let me know what version of the provider you're using?

**Comment by zjaniga** [comment]
Hi @mega-alex,
I was using 0.4.1, then upgraded to 1.0.0-beta1 and now upgraded to 1.0.0 and prefix-list is still not part of the state file after importing the resource.

**Comment by mega-alex** [comment]
Can you give this a try with the `v1.0.0-rc1` release?

**Comment by zjaniga** [comment]
The list is now visible, but the entries are still missing:

`prefix_filter_lists    = [
        {
            address_family = "IPv4"
            description    = "AZ to AWS Updated 10-9"
            id             = 2544
        },
    ]`

**Comment by mega-alex** [comment]
Prefix lists can now be created, modified, and deleted for MCRs in the `v1.0.1` release. Mind giving it a try and letting me know if it fixed your issue?

**Comment by zjaniga** [comment]
Hi @mega-alex, I can confirm it is now visible now in the state file. Did not try to edit and apply changes yet, but will work on it in a few weeks.
Thank you for your help!

**Comment by mega-alex** [comment]
Great, closing this issue then. If it is still a problem feel free to reopen it.
